// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestLinq;

namespace TestLinq.Migrations
{
    [DbContext(typeof(TestDbContext))]
    [Migration("20190611022233_add_id_generator")]
    partial class add_id_generator
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TestLinq.Entity.Blog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Name");

                    b.Property<Guid>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Blogs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a359271c-eeb6-4526-a0ca-93ed5201472d"),
                            Name = "batanvlog",
                            UserId = new Guid("031e8be9-24d5-4f2b-acb0-22ca385b27dd")
                        });
                });

            modelBuilder.Entity("TestLinq.Entity.Post", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("NEWID()");

                    b.Property<Guid>("BlogId");

                    b.Property<string>("Content");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("BlogId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d726fa75-0b36-4726-81fd-dc8111b76344"),
                            BlogId = new Guid("a359271c-eeb6-4526-a0ca-93ed5201472d"),
                            Content = "Cac chau oi ...",
                            Name = "100 canh ga chien nuoc mam"
                        });
                });

            modelBuilder.Entity("TestLinq.Entity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("031e8be9-24d5-4f2b-acb0-22ca385b27dd"),
                            Name = "batan"
                        });
                });

            modelBuilder.Entity("TestLinq.Entity.Blog", b =>
                {
                    b.HasOne("TestLinq.Entity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TestLinq.Entity.Post", b =>
                {
                    b.HasOne("TestLinq.Entity.Blog", "Blog")
                        .WithMany("Posts")
                        .HasForeignKey("BlogId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
